{{- if and .Values.gitlab.token (not .Values.gitlab.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-reviewer.fullname" . }}-gitlab
  labels:
    {{- include "code-reviewer.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.gitlab.token | b64enc | quote }}
{{- end }}
