apiVersion: v1
kind: Service
metadata:
  name: {{ include "code-reviewer.fullname" . }}-server
  labels:
    {{- include "code-reviewer.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "code-reviewer.serverSelectorLabels" . | nindent 4 }}
